logging:
  file:
    enable: true
    level: INFO
    path: logs
    rotation: "10 MB"
    retention: "7 days"
  console:
    enable: true
    level: INFO

db_meta:
  host: localhost
  port: 3306
  user: sirmem
  password: 123456
  database: meta

db_dw:
  host: localhost
  port: 3306
  user: sirmem
  password: 123456
  database: dw

qdrant:
  host: localhost
  port: 6333
  embedding_size: 1024

embedding:
  base_url: https://api.siliconflow.cn/v1
  model: BAAI/bge-large-en-v1.5
  api_key: ${oc.env:EMBEDDING_API_KEY,""}

es:
  host: localhost
  port: 9200
  index_name: data_agent

#TODO 填上自己的模型API
llm:
  model_name: gpt-5.2-codex
  api_key: <api_key>
  base_url: https://api.openai-proxy.org/v1
